### ISSUE TITLE
problema di versione

### ISSUE THREAD

**Issue by fabiodelogu** [c-hydro/door#9]
ciao @AndreaLibe  la versione 1.0.1 è precedente alla versione 1.0.0
se effettivamente quella più aggiornata è al 1.0.0 direi che possiamo
rimuovere la 1.0.1 ... oppure bisogna fare dei controlli?

**Comment by AndreaLibe** [comment]
L'ho eliminata, era un errore, me n'ero accorto e avevo già fatot i controlli e l'allineamento ma poi mi sono dimenticato di cancellarla! Grazie!
